import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="p-6 md:p-12 bg-gray-50 text-gray-800">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-6 text-center text-blue-600">Terms and Conditions for SmartCare App</h1>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">1. Introduction</h2>
          <p>
            Welcome to SmartCare! These Terms and Conditions ("Terms") govern your
            use of the SmartCare application ("App") and its associated services
            ("Services"). By using the App, you agree to comply with these Terms.
            If you do not agree, please do not use the App.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">2. About SmartCare</h2>
          <p>
            SmartCare is a comprehensive health management app designed to help
            users monitor their health metrics, track progress over time, and
            access personalized health insights. Please note that SmartCare is
            not a substitute for professional medical advice, diagnosis, or
            treatment. Always consult a qualified healthcare provider for any
            medical concerns.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">3. User Accounts</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>Provide accurate and up-to-date information.</li>
            <li>Maintain the confidentiality of your login credentials.</li>
            <li>Notify us immediately of any unauthorized use of your account.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">4. Privacy Policy</h2>
          <p>
            Your privacy is important to us. By using the App, you consent to the
            collection, use, and disclosure of your personal data as described in
            our Privacy Policy, which is incorporated into these Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">5. Use of the App</h2>
          <p>You agree to use the App only for lawful purposes and in accordance with these Terms. Prohibited uses include but are not limited to:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>Violating any applicable laws or regulations.</li>
            <li>Interfering with the security or functionality of the App.</li>
            <li>Uploading or sharing content that is harmful, offensive, or inappropriate.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">6. Health Information</h2>
          <p>
            While SmartCare provides tools to monitor and track your health, the
            information and insights generated by the App are for informational
            purposes only. They are not intended to replace professional medical
            advice.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">7. Subscription and Payments</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>Pay all applicable fees as outlined in the App.</li>
            <li>Provide accurate billing information.</li>
            <li>Understand that subscriptions may automatically renew unless canceled as per the cancellation policy.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">8. Intellectual Property</h2>
          <p>
            All content, trademarks, logos, and intellectual property associated with SmartCare are owned by us or our licensors. You may not use, reproduce, or distribute any of this material without our explicit permission.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">9. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, SmartCare and its affiliates
            are not liable for any direct, indirect, incidental, or consequential
            damages arising from your use of the App.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">10. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the App at
            our discretion, without notice, if you violate these Terms or engage
            in prohibited activities.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">11. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. The latest version will
            always be available in the App. Continued use of the App constitutes
            acceptance of the updated Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">12. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with the laws
            of Nigeria, without regard to its conflict of law principles.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-2">13. Contact Us</h2>
          <p>
            If you have any questions or concerns about these Terms, please
            contact us at:
          </p>
          <p className="mt-4">
            <strong>SmartCare Support Team</strong>
            <br />
            Email: <a href="mailto:support@sunsystems.ng" className="text-blue-600">support@sunsystems.ng</a>
          </p>
        </section>

        <p className="text-sm text-gray-600 text-center mt-8">
          By using SmartCare, you acknowledge that you have read, understood, and
          agree to these Terms and Conditions.
        </p>
      </div>
    </div>
  );
};

export default TermsAndConditions;
